apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

namespace: abuse-api-dev

patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/1"
      value:
        name: wiremock
        image: gdartifactory1.jfrog.io/docker-dcu-local/zeus/wiremock:dev
  target:
    kind: Deployment
    name: zeus

images:
- name: gdartifactory1.jfrog.io/docker-dcu-local/zeus
  newTag: dev

configMapGenerator:
- literals:
  - sysenv=dev
  - ELASTIC_APM_ENVIRONMENT=dev
  name: env-specific-values
