services:
  zeus:
    image: docker-dcu-local.artifactory.secureserver.net/zeus:dev
    environment:
      BROKER_URL: ${BROKER_URL}
      QUEUE_TYPE: 'quorum'
      # TODO CMAPT-5272: remove all DIABLO*, PLESK4*, and VPS4* variables
      CMAP_API_CERT: '/tmp/certs/apiuser.cmap.int.godaddy.com.crt'
      CMAP_API_KEY: '/tmp/certs/apiuser.cmap.int.godaddy.com.key'
      DB_PASS: ${DB_PASS}
      DIABLOPASS: ${DIABLOPASS}
      DIABLOUSER: ${DIABLOUSER}
      DISABLESSL: 'True'
      EMAIL_RECIPIENT: ${EMAIL_RECIPIENT}
      PLESKPASS: ${PLESKPASS}
      PLESKUSER: ${PLESKUSER}
      REDIS: redis
      sysenv: dev
      VPS4PASS: ${VPS4PASS}
      VPS4USER: ${VPS4USER}
      ZEUS_CLIENT_CERT: '/tmp/certs/zeus.client.cset.int.dev-gdcorp.tools.crt'
      ZEUS_CLIENT_KEY: '/tmp/certs/zeus.client.cset.int.dev-gdcorp.tools.key'
    volumes:
      - /PATH_TO_YOUR_CERTS_DIRECTORY/:/tmp/certs/
    links:
      - redis:redis
      - rabbitmq:rabbitmq
    depends_on:
      - rabbitmq
      - redis

  rabbitmq:
    image: rabbitmq:3.8.14-management
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:6.2.1
    ports:
      - 6379:6379