version: 1

disable_existing_loggers: False

formatters:
    simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    detailed:
        format: '[%(levelname)s:%(asctime)s:%(filename)s:%(lineno)s - %(funcName)20s() ] %(message)s'
        datefmt:  '%Y-%m-%d %I:%M:%S%p'


handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: detailed
        stream: ext://sys.stdout

    mongo_log_handler:
        class: mongohandler.MongoLogFactory
        level: ext://zeus.events.user_logging.user_logger.UEVENT


# define logging levels, and logging handlers for your modules here
# each section should define a logging setup for a specific module in
# your code. If you dont define any loggers, the root logger will process
# the logging messages
loggers:
    contact:
        level: INFO
        handlers: [console, mongo_log_handler]
        propagate: no
# The logger for the root level directory, which is 'zeus'
root:
    level: INFO
    handlers: [console, mongo_log_handler]