apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

namespace: abuse-api-prod

images:
- name: docker-dcu-local.artifactory.secureserver.net/zeus
  newTag: prod

configMapGenerator:
- literals:
  - sysenv=prod
  - GOCENTRAL_URL='https://services.orion.prod.secureserver.net/account/accountoperations.asmx'
  name: env-specific-values