---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "zeus"
  namespace: "abuse-api-prod"
  labels:
    app: "zeus"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: "zeus"
  template:
    metadata:
      labels:
        app: "zeus"
    spec:
      imagePullSecrets:
        -
          name: "dcu-artifactory-creds"
      containers:
        -
          name: "zeus"
          imagePullPolicy: "Always"
          image: "docker-dcu-local.artifactory.secureserver.net/zeus:REPLACE_WITH_GIT_COMMIT"
          livenessProbe:
            exec:
              command:
                - '/app/health.sh'
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
          - name: BUILD_DATE
            value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
          - name: sysenv
            value: prod
          - name: GOCENTRAL_URL
            value: 'https://services.orion.prod.secureserver.net/account/accountoperations.asmx'
          - name: BROKER_PASS
            valueFrom:
              secretKeyRef:
                name: amqp-shared-creds
                key: password
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-phishstory-v2
                key: password
          - name: DB_KELVIN_PASS
            valueFrom:
              secretKeyRef:
                name: db-kelvin-v2
                key: password

          - name: DIABLOUSER
            valueFrom:
              secretKeyRef:
                name: auth-zeus-envs
                key: diablouser
          - name: DIABLOPASS
            valueFrom:
              secretKeyRef:
                name: auth-zeus-envs
                key: diablopass
          - name: PLESKUSER
            valueFrom:
              secretKeyRef:
                name: auth-zeus-envs
                key: pleskuser
          - name: PLESKPASS
            valueFrom:
              secretKeyRef:
                name: auth-zeus-envs
                key: pleskpass
          - name: MWPONEUSER
            valueFrom:
              secretKeyRef:
                name: mwp-one-creds-v2
                key: mwponeuser
          - name: MWPONEPASS
            valueFrom:
              secretKeyRef:
                name: mwp-one-creds-v2
                key: mwponepass
          - name: VPS4USER
            valueFrom:
              secretKeyRef:
                name: auth-vps4-api
                key: vps4user
          - name: VPS4PASS
            valueFrom:
              secretKeyRef:
                name: auth-vps4-api
                key: vps4pass
          - name: CMAP_PROXY_USER
            valueFrom:
              secretKeyRef:
                name: auth-cmap-proxy
                key: username
          - name: CMAP_PROXY_PASS
            valueFrom:
              secretKeyRef:
                name: auth-cmap-proxy
                key: password
          - name: SLACK_HANDLER
            valueFrom:
              secretKeyRef:
                name: zeus-slack
                key: handler
          - name: CMAP_PROXY_CERT
            value: /proxycerts/tls.crt
          - name: CMAP_PROXY_KEY
            value: /proxycerts/tls.key

          - name: OCM_SSL_CERT
            value: /ocm_certs/tls.crt
          - name: OCM_SSL_KEY
            value: /ocm_certs/tls.key
          - name: ZEUS_SSL_CERT
            value: /zeus_certs/tls.crt
          - name: ZEUS_SSL_KEY
            value: /zeus_certs/tls.key
          - name: GOCENTRAL_SSL_CERT
            value: /ecomm_certs/tls.crt
          - name: GOCENTRAL_SSL_KEY
            value: /ecomm_certs/tls.key
          - name: RESULT_BACKEND_HOSTNAME
            value: godaddy-service-redis.abuse-api-prod.svc.cluster.local

          volumeMounts:
          - name: tls-ocm-files
            mountPath: /ocm_certs
            readOnly: true
          - name: tls-zeus-files
            mountPath: /zeus_certs
            readOnly: true
          - name: tls-files-proxy
            mountPath: /proxycerts
            readOnly: true
          - name: tls-ecomm-files
            mountPath: /ecomm_certs
            readOnly: true

        -
          name: "redis"
          imagePullPolicy: "Always"
          image: "redis"
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 15
            timeoutSeconds: 5

      volumes:
        - name: tls-ocm-files
          secret:
            secretName: tls-phishnet
        - name: tls-zeus-files
          secret:
            secretName: tls-zeus
        - name: tls-files-proxy
          secret:
            secretName: tls-cmap-auth
        - name: tls-ecomm-files
          secret:
            secretName: tls-ecomm
