---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "zeus"
  labels:
    app: "zeus"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: "zeus"
  template:
    metadata:
      labels:
        app: "zeus"
    spec:
      imagePullSecrets:
        - name: "dcu-artifactory-creds"
      containers:
        - name: "zeus"
          image: "docker-dcu-local.artifactory.secureserver.net/zeus"
          envFrom:
            - configMapRef:
                name: env-specific-values
          livenessProbe:
            exec:
              command:
                - '/app/health.sh'
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
          - name: MULTIPLE_BROKERS
            valueFrom:
              secretKeyRef:
                name: amqp-shared-creds
                key: multiple_brokers_grandma
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-phishstory-v2
                key: password
          - name: DB_KELVIN_PASS
            valueFrom:
              secretKeyRef:
                name: db-kelvin-v2
                key: password
          - name: CMAP_API_CERT
            value: /apicerts/tls.crt
          - name: CMAP_API_KEY
            value: /apicerts/tls.key
          - name: SLACK_HANDLER
            valueFrom:
              secretKeyRef:
                name: zeus-slack
                key: handler
          - name: OCM_SSL_CERT
            value: /ocm_certs/tls.crt
          - name: OCM_SSL_KEY
            value: /ocm_certs/tls.key
          - name: ZEUS_CLIENT_CERT
            value: /zeus_client_certs/tls.crt
          - name: ZEUS_CLIENT_KEY
            value: /zeus_client_certs/tls.key
          - name: ELASTIC_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: apm-access
                key: url
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: apm-access
                key: secret
          volumeMounts:
          - name: tls-files-api
            mountPath: /apicerts
            readOnly: true
          - name: tls-ocm-files
            mountPath: /ocm_certs
            readOnly: true
          - name: tls-zeus-client-cert-files
            mountPath: /zeus_client_certs
            readOnly: true

        -
          name: "redis"
          image: "redis"
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 15
            timeoutSeconds: 5

      volumes:
        - name: tls-ocm-files
          secret:
            secretName: tls-phishnet
        - name: tls-zeus-client-cert-files
          secret:
            secretName: tls-zeus-client-cert
        - name: tls-files-api
          secret:
            secretName: tls-cmap-api
