---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "zeus"
  labels:
    app: "zeus"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: "zeus"
  template:
    metadata:
      labels:
        app: "zeus"
    spec:
      imagePullSecrets:
        - name: "dcu-artifactory-creds"
      containers:
        - name: "zeus"
          image: "docker-dcu-local.artifactory.secureserver.net/zeus"
          envFrom:
            - configMapRef:
                name: env-specific-values
          livenessProbe:
            exec:
              command:
                - '/app/health.sh'
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
          - name: MULTIPLE_BROKERS
            valueFrom:
              secretKeyRef:
                name: amqp-shared-creds
                key: multiple_brokers_grandma
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-phishstory-v2
                key: password
          - name: DB_KELVIN_PASS
            valueFrom:
              secretKeyRef:
                name: db-kelvin-v2
                key: password

          - name: DIABLOUSER
            valueFrom:
              secretKeyRef:
                name: auth-zeus-envs
                key: diablouser
          - name: DIABLOPASS
            valueFrom:
              secretKeyRef:
                name: auth-zeus-envs
                key: diablopass
          - name: PLESKUSER
            valueFrom:
              secretKeyRef:
                name: auth-zeus-envs
                key: pleskuser
          - name: PLESKPASS
            valueFrom:
              secretKeyRef:
                name: auth-zeus-envs
                key: pleskpass
          - name: CMAP_API_CERT
            value: /apicerts/tls.crt
          - name: CMAP_API_KEY
            value: /apicerts/tls.key
          - name: VPS4USER
            valueFrom:
              secretKeyRef:
                name: auth-vps4-api
                key: vps4user
          - name: VPS4PASS
            valueFrom:
              secretKeyRef:
                name: auth-vps4-api
                key: vps4pass
          - name: CMAP_PROXY_USER
            valueFrom:
              secretKeyRef:
                name: auth-cmap-proxy
                key: username
          - name: CMAP_PROXY_PASS
            valueFrom:
              secretKeyRef:
                name: auth-cmap-proxy
                key: password
          - name: SLACK_HANDLER
            valueFrom:
              secretKeyRef:
                name: zeus-slack
                key: handler
          - name: CMAP_PROXY_CERT
            value: /proxycerts/tls.crt
          - name: CMAP_PROXY_KEY
            value: /proxycerts/tls.key
          - name: OCM_SSL_CERT
            value: /ocm_certs/tls.crt
          - name: OCM_SSL_KEY
            value: /ocm_certs/tls.key
          - name: ZEUS_SSL_CERT
            value: /zeus_certs/tls.crt
          - name: ZEUS_SSL_KEY
            value: /zeus_certs/tls.key
          - name: GOCENTRAL_SSL_CERT
            value: /ecomm_certs/tls.crt
          - name: GOCENTRAL_SSL_KEY
            value: /ecomm_certs/tls.key
          - name: RESULT_BACKEND_HOSTNAME
            value: godaddy-service-redis.abuse-api-dev.svc.cluster.local
          - name: ELASTIC_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: apm-access
                key: url
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: apm-access
                key: secret
          - name: ELASTIC_APM_ENVIRONMENT
            value: dev
          volumeMounts:
          - name: tls-files-api
            mountPath: /apicerts
            readOnly: true
          - name: tls-ocm-files
            mountPath: /ocm_certs
            readOnly: true
          - name: tls-zeus-files
            mountPath: /zeus_certs
            readOnly: true
          - name: tls-files-proxy
            mountPath: /proxycerts
            readOnly: true
          - name: tls-ecomm-files
            mountPath: /ecomm_certs
            readOnly: true

        -
          name: "redis"
          image: "redis"
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 15
            timeoutSeconds: 5

      volumes:
        - name: tls-ocm-files
          secret:
            secretName: tls-phishnet
        - name: tls-zeus-files
          secret:
            secretName: tls-zeus
        - name: tls-files-proxy
          secret:
            secretName: tls-cmap-auth
        - name: tls-ecomm-files
          secret:
            secretName: tls-ecomm
        - name: tls-files-api
          secret:
            secretName: tls-cmap-api
