---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "zeus"
  labels:
    app: "zeus"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: "zeus"
  template:
    metadata:
      labels:
        app: "zeus"
    spec:
      imagePullSecrets:
        - name: "dcu-artifactory-creds"
      containers:
        - name: "zeus"
          image: "docker-dcu-local.artifactory.secureserver.net/zeus"
          envFrom:
            - configMapRef:
                name: env-specific-values
          livenessProbe:
            exec:
              command:
                - '/app/health.sh'
            periodSeconds: 20
            timeoutSeconds: 10
          env:
          - name: MULTIPLE_BROKERS
            valueFrom:
              secretKeyRef:
                name: amqp-shared-creds
                key: multiple_brokers_grandma
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-phishstory-v2
                key: password
          - name: DB_KELVIN_PASS
            valueFrom:
              secretKeyRef:
                name: db-kelvin-v2
                key: password
          # TODO CMAPT-5272: Remove DIABLOUSER, DIABLOPASS, PLESKUSER, PLESKPASS,
          #     VPS4USER, VPS4PASS, VERTIGO_USER and VERTIGO_PASS
          - name: DIABLOUSER
            valueFrom:
              secretKeyRef:
                name: auth-zeus-envs
                key: diablouser
          - name: DIABLOPASS
            valueFrom:
              secretKeyRef:
                name: auth-zeus-envs
                key: diablopass
          - name: PLESKUSER
            valueFrom:
              secretKeyRef:
                name: auth-zeus-envs
                key: pleskuser
          - name: PLESKPASS
            valueFrom:
              secretKeyRef:
                name: auth-zeus-envs
                key: pleskpass
          - name: CMAP_API_CERT
            value: /apicerts/tls.crt
          - name: CMAP_API_KEY
            value: /apicerts/tls.key
          - name: VPS4USER
            valueFrom:
              secretKeyRef:
                name: auth-vps4-api
                key: vps4user
          - name: VPS4PASS
            valueFrom:
              secretKeyRef:
                name: auth-vps4-api
                key: vps4pass
          - name: VERTIGO_USER
            valueFrom:
              secretKeyRef:
                name: auth-hosting-envs
                key: vertigouser
          - name: VERTIGO_PASS
            valueFrom:
              secretKeyRef:
                name: auth-hosting-envs
                key: vertigopass
          - name: SLACK_HANDLER
            valueFrom:
              secretKeyRef:
                name: zeus-slack
                key: handler
          # TODO CMAPT-5272: remove the nes-on-flag variables
          - name: ANGELO_USE_NES
            valueFrom:
              configMapKeyRef:
                name: nes-on-flag
                key: angelo
          - name: DIABLO_USE_NES
            valueFrom:
              configMapKeyRef:
                name: nes-on-flag
                key: diablo
          - name: GOCENTRAL_USE_NES
            valueFrom:
              configMapKeyRef:
                name: nes-on-flag
                key: gocentral
          - name: MWPONE_USE_NES
            valueFrom:
              configMapKeyRef:
                name: nes-on-flag
                key: mwpone
          - name: VERTIGO_USE_NES
            valueFrom:
              configMapKeyRef:
                name: nes-on-flag
                key: vertigo
          - name: VPS4_USE_NES
            valueFrom:
              configMapKeyRef:
                name: nes-on-flag
                key: vps4
          - name: ALL_USE_NES
            valueFrom:
              configMapKeyRef:
                name: nes-on-flag
                key: all
          # TODO CMAPT-5272: remove CMAP_PROXY_CERT, CMAP_PROXY_KEY, GOCENTRAL_SSL_CERT and GOCENTRAL_SSL_KEY
          #    as well as the volume and volume mounts associated with those
          - name: ZEUS_CLIENT_CERT
            value: /zeus_client_certs/tls.crt
          - name: ZEUS_CLIENT_KEY
            value: /zeus_client_certs/tls.key
          - name: GOCENTRAL_SSL_CERT
            value: /ecomm_certs/tls.crt
          - name: GOCENTRAL_SSL_KEY
            value: /ecomm_certs/tls.key
          - name: ELASTIC_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: apm-access
                key: url
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: apm-access
                key: secret
          - name: MONGO_CLIENT_CERT
            value: /mongo_common_certs/mongo_client.pem
          volumeMounts:
          - name: tls-files-api
            mountPath: /apicerts
            readOnly: true
          - name: tls-zeus-client-cert-files
            mountPath: /zeus_client_certs
            readOnly: true
          - name: tls-ecomm-files
            mountPath: /ecomm_certs
            readOnly: true
          - name: tls-mongo-common-cert-files
            mountPath: /mongo_common_certs
            readOnly: true

        -
          name: "redis"
          image: "redis"
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 15
            timeoutSeconds: 5

      volumes:
        - name: tls-zeus-client-cert-files
          secret:
            secretName: tls-zeus-client-cert
        - name: tls-ecomm-files
          secret:
            secretName: tls-ecomm
        - name: tls-files-api
          secret:
            secretName: tls-cmap-api
        - name: tls-mongo-common-cert-files
          secret:
            secretName: tls-mongo-common-cert-files